### ISSUE TITLE
Download to linux

### ISSUE THREAD

**Issue by gorogm** [VCCIV/BLVD#1]
Dear BLVD-group,
Is it possible to download the data to linux and without a baidu account? As we tried to download the data it offered only an .exe to download. Which labels should we click on to access the data after logging in?

**Comment by JWFangit** [comment]
Thanks for your attention. We are preparing the download linking for Linux. They will be released later.

**Comment by zolika84** [comment]
Dear JWFangit,
Same issue for me. If it is possible could you upload to another storage?

**Comment by VCCIV** [comment]
Thanks for your attention. We have uploaded to google drive.

**Comment by KevinLADLee** [comment]
> Dear BLVD-group,
> Is it possible to download the data to linux and without a baidu account? As we tried to download the data it offered only an .exe to download. Which labels should we click on to access the data after logging in?

FYI: https://github.com/iikira/BaiduPCS-Go
