### ISSUE TITLE
show targets in lidar coordinate

### ISSUE THREAD

**Issue by hu2011** [VCCIV/BLVD#2]
Hi, thanks very much for your work and it's useful for most people.
But there are some problems when using your dataset.
I am wondering why the boxes3d dimensions of vehicle in label are  small , compared to (l w h : 3.9,1.6,1.56 in kitti). It doesn't seem to contain a full target object.
 I want to show lidar with ground truth boxes in lidar coords, the below is output of compute_box_corners_3d. The target box is not in the right direction. The length of x aixs is 0.94. the minimum and maximum are not the same as that in label. 

Can you kindly tell me what's wrong and show us an example of drawing lidar with gt boxes? Thank you very much.

Label.txt
1 3 5 2 11 9.915727 -3.910213 2.288099 0.942343 3.432148 0.000000 -2.193600 -0.496231

Calib.print_object()
3d bbox h,w,l: 1.697369, 0.942343, 2.288099
3d bbox location, ry: (9.915727, -3.910213, -1.344915), (1.000000,0.000000)

Results of compute_box_corners_3d
box3d_velo: [[10.3868985 -3.910213  -2.488965 ]
 [ 9.4445555 -3.910213  -2.488965 ]
 [ 9.4445555 -3.910213  -0.200866 ]
 [10.3868985 -3.910213  -0.200866 ]
 [10.3868985 -5.607582  -2.488965 ]
 [ 9.4445555 -5.607582  -2.488965 ]
 [ 9.4445555 -5.607582  -0.200866 ]
 [10.3868985 -5.607582  -0.200866 ]]

**Comment by JWFangit** [comment]
Thanks. The length and width value in the label files are the half of the total size.

**Comment by dxjforyou** [comment]
I have fixed the bug in utils.py
![image](https://user-images.githubusercontent.com/24803477/56489909-f58eb600-6515-11e9-8971-dd290f482101.png)
![image](https://user-images.githubusercontent.com/24803477/56489935-0808ef80-6516-11e9-8e04-fded7ba2a8a1.png)
![微信截图_20190422154042](https://user-images.githubusercontent.com/24803477/56489977-2969db80-6516-11e9-91f5-77f0c0dc3ea3.png)

**Comment by hu2011** [comment]
Thanks.
